CREATE TABLE inscripto
(
  id serial NOT NULL primary key,
  nombre character varying,
  apellido character varying,
  tipo_dni integer references tipo_dni(id),
  nrodni character varying,
  direccion character varying,
  numero character varying,
  piso character varying,
  dpto character varying,
  localidad character varying,
  mail character varying,
  telfijo character varying,
  telcel character varying,  
  razon_social character varying,
  titaca character varying, 
  fechainscripto date,
  info character varying,
  actividad1 boolean,
  actividad2 boolean,
  actividad3 boolean,
  actividad4 boolean,
  actividad5 boolean,
  actividad6 boolean,
  actividad7 boolean,
  actividad8 boolean,
  actividad9 boolean,
  actividad10 boolean,
  actividad11 boolean,
  actividad12 boolean
);